import collections

holdem_player_hand = collections.namedtuple('HPCards', ['rank', 'paired', 'suited', 'combos', 'combo_percent', 'win_percent'])

def xvalues(rank):
    return 0

def suitedvalues(stringrank):
    hmh = holdem_player_hand(
            rank=0, paired=False, suited=True, 
            combos=4, combo_percent=.30, win_percent=0)
    if stringrank == 'AK':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == 'AQ':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == 'AJ':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == 'AT':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == 'A9':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == 'A8':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == 'A7':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == 'A6':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == 'A5':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == 'A4':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == 'A3':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == 'A2':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == 'KQ':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == 'KJ':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == 'KT':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == 'K9':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == 'K8':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == 'K7':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == 'K6':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == 'K5':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == 'K4':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == 'K3':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == 'K2':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == 'QJ':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == 'QT':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == 'Q9':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == 'Q8':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == 'Q7':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == 'Q6':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == 'Q5':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == 'Q4':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == 'Q3':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == 'Q2':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == 'JT':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == 'J9':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == 'J8':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == 'J7':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == 'J6':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == 'J5':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == 'J4':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == 'J3':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == 'J2':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == 'T9':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == 'T8':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == 'T7':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == 'T6':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == 'T5':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == 'T4':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == 'T3':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == 'T2':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == '98':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == '97':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == '96':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == '95':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == '94':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == '93':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == '92':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == '87':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == '86':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == '85':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == '84':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == '83':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == '82':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == '76':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == '75':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == '74':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == '73':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == '72':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == '65':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == '64':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == '63':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == '62':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == '54':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == '53':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == '52':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == '43':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == '42':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == '32':
        hmh = hmh._replace(rank=1, win_percent=22)
    else:
        hmh = hmh._replace(rank=200, win_percent=3)
    return hmh

def unsuitedvalues(stringrank):
    hmh = holdem_player_hand(
        rank=0, paired=False, suited=False, 
        combos=12, combo_percent=.90, win_percent=0)
    if stringrank == 'AK':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == 'AQ':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == 'AJ':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == 'AT':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == 'A9':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == 'A8':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == 'A7':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == 'A6':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == 'A5':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == 'A4':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == 'A3':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == 'A2':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == 'KQ':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == 'KJ':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == 'KT':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == 'K9':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == 'K8':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == 'K7':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == 'K6':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == 'K5':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == 'K4':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == 'K3':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == 'K2':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == 'QJ':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == 'QT':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == 'Q9':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == 'Q8':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == 'Q7':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == 'Q6':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == 'Q5':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == 'Q4':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == 'Q3':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == 'Q2':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == 'JT':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == 'J9':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == 'J8':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == 'J7':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == 'J6':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == 'J5':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == 'J4':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == 'J3':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == 'J2':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == 'T9':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == 'T8':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == 'T7':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == 'T6':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == 'T5':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == 'T4':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == 'T3':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == 'T2':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == '98':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == '97':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == '96':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == '95':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == '94':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == '93':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == '92':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == '87':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == '86':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == '85':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == '84':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == '83':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == '82':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == '76':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == '75':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == '74':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == '73':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == '72':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == '65':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == '64':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == '63':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == '62':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == '54':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == '53':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == '52':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == '43':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == '42':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == '32':
        hmh = hmh._replace(rank=1, win_percent=22)
    else:
        hmh = hmh._replace(rank=200, win_percent=3)
    return hmh
    
def pairedvalues(stringrank):
    hmh = holdem_player_hand(
            rank=0, paired=False, suited=True, 
            combos=4, combo_percent=.30, win_percent=0)
    if stringrank == 'AA':
        hmh = hmh._replace(rank=1, win_percent=22)
    elif stringrank == 'KK':
        hmh = hmh._replace(rank=1, win_percent=22)
    else:
        hmh = hmh._replace(rank=200, win_percent=3)
    return hmh